### ISSUE TITLE
every bookmarks i have is deleted

### ISSUE THREAD

**Issue by karma1428** [OlegWock/anori#108]
everything is gone. even my backup is not working. it's only giving me a blank folder! it still have my folder icon and folder name but the bookmarks is gone... 

what is happening? is this fixable?

**Comment by OlegWock** [comment]
Yes, this is fixable. Could you send me backup you're trying to load? You can share it here or send to my email oleh@sinja.io if you don't want to share it publicly

Widgets system has been changed in recent version, your widgets should be automatically updated when extension updates, but if you apply backup from older version it might cause this issue. I check your backup and update it to comply with latest version of the extension, so you will be able to load it.

**Comment by karma1428** [comment]
> 

[Anori.zip](https://github.com/OlegWock/anori/files/12342318/Anori.zip)

**Comment by OlegWock** [comment]
@karma1428 try importing this backup

[restored_backup.zip](https://github.com/OlegWock/anori/files/12342539/restored_backup.zip)

**Comment by mauriciotrooh** [comment]
Hello @OlegWock I'm having the same issue. Do you mind helping me, please?
[anori-backup-16-08-2023_14-40.zip](https://github.com/OlegWock/anori/files/12362515/anori-backup-16-08-2023_14-40.zip)

**Comment by OlegWock** [comment]
@mauriciotrooh here you go

[anori-restored-backup.zip](https://github.com/OlegWock/anori/files/12363026/anori-restored-backup.zip)
