### ISSUE TITLE
Onboard widget flashes upon opening new tab

### ISSUE THREAD

**Issue by Lotsofleaves** [OlegWock/anori#12]
Even when the dashboard space is full of other widgets, the Onboarding widget flashes briefly and disappears when opening a new tab.

I encountered this bug using both Firefox and Chrome

**Comment by OlegWock** [comment]
It's a known issue and essentially it all boils to performance #1 (so I'm closing this issue in favor of #1)
It's on my roadmap but I'm not sure how much I'll be able to optimize it (without major rewriting), so there is a chance that it will be still present even after optimizations, it all depends on how fast your laptop is

Onboarding card is shown if you don't have widgets in folder, this includes short timespan between page initialization and loading your widgets from extension's storage. This might be more noticeable on not very powerful laptops
