### ISSUE TITLE
Day name problem in calendar

### ISSUE THREAD

**Issue by kiznick** [OlegWock/anori#120]
In Thai language, every name of the day starts with "วัน", or it means day in English, and the calendar shows like this:
![image](https://github.com/OlegWock/anori/assets/22832362/b8dbfc56-20f4-454c-9e18-fb2bef3bc07e)
I have two options to present.

1. Just remove "วัน" from name of day
2. Add a new i18n key for abbreviated day name

What should I do?

**Comment by OlegWock** [comment]
I think I can just modify calendar code to ignore 'วัน', this way we'll still have correct day names in translation files in case we'll need them in other places

**Comment by OlegWock** [comment]
@kiznick is this correct?

![CleanShot 2023-08-25 at 11 08 32](https://github.com/OlegWock/anori/assets/7430438/91e7b5d2-e17f-4b81-88d9-b635f8af87b4)

**Comment by kiznick** [comment]
> @kiznick is this correct?
> 
> ![CleanShot 2023-08-25 at 11 08 32](https://github.com/OlegWock/anori/assets/7430438/91e7b5d2-e17f-4b81-88d9-b635f8af87b4)
> 

In Thai, we use "จ" "อ" "พ" "พฤ" "ศ" "ส" "อา" because some day name have same first character.

**Comment by OlegWock** [comment]
I just realized we already have weekdays (both full and short) in moment locales, so I switched calendar to use those, no need to change anything in translation

**Comment by kiznick** [comment]
> I just realized we already have weekdays (both full and short) in moment locales, so I switched calendar to use those, no need to change anything in translation

Ok, Thanks.

**Comment by OlegWock** [comment]
Fixed in v1.13.0. I uploaded it to stores, but it will take a few more days to get reviewed and updated
