### ISSUE TITLE
Immersive mode [Feature request]

### ISSUE THREAD

**Issue by Crunchbits** [OlegWock/anori#123]
I think it'd be great to have an option that makes pages fill up almost all of the space. For example, currently if you make a folder that only has an Embed webpage (that covers as much as possible) you will still have a lot of unnecessary space:
- the padded border that surrounds the widget
- the padded border that shows the title name of the folder and edit button
- the non-compact sidebar
- the background image

I think an option to hide these elements so that you maximize space would be very good. Hence the name 'Immersive mode'. This would especially be useful for Embed webpages that have a lot of information. Currently these pages are prone to squish content or be cropped in ways that require you to scroll to see more content instead of just at a glance. This would fix that issue.

Also if this were to be implemented, while I think that having the sidebar  popup on hover would be a nice choice to effectively make it 100% full screen, I think it would be more useful to have a sidebar that is always visible but very compact/thin. That is, if I had to choose from the two options.

**Comment by OlegWock** [comment]
Hello Crunchbits, thanks for suggestion (and sorry for late reply!). 

Anori was made to let users compose their page using a bunch of tiny widgets, and in this case all paddings and gaps works as "negative space" and helps UI to stay uncluttered and easily navigable. Of course this doesn't work well when you have one big widget, but it was never a main use-case for Anori and not something I was aiming for when making this extension. 

Taking this into account, I don't think 'Immersive mode' has a place in Anori
