### ISSUE TITLE
Unable to download [ still unable to download ]

### ISSUE THREAD

**Issue by Mistlion01** [OlegWock/anori#124]
![image](https://github.com/OlegWock/anori/assets/87451493/e43b6beb-0847-44fe-a6c1-094d8c008fec)

I cannot download the extension and have no trouble downloading others.

**Comment by Mistlion01** [comment]
Hi, I am still not able to download specifically this extension.

**Comment by Mistlion01** [comment]
![image](https://github.com/OlegWock/anori/assets/87451493/fa38f2d0-0664-491d-a401-392317ce2a5b)
![image](https://github.com/OlegWock/anori/assets/87451493/4014de6a-c74a-414e-beff-a8dd10df3f2b)

I am able to download other extensions and apps. This is the ONLY thing there is a problem with, please help! I've wanted to download this for a long time

**Comment by OlegWock** [comment]
@Mistlion01 did you tried this https://www.youtube.com/watch?v=scUzYGR75do ?
