### ISSUE TITLE
Time Widget

### ISSUE THREAD

**Issue by baroque-yachts** [OlegWock/anori#130]
Time format options are confusing. The 12 hours and 24 hours format is not indicated properly.
Could be better to select separately the following items: 

- 12 HR or 24hr
- the am/pm or AM/PM
- with seconds or without seconds

![image](https://github.com/OlegWock/anori/assets/145041629/dfd1b77b-827a-435e-abbd-86a51931a60f)

**Comment by OlegWock** [comment]
I added a few more time formatting options (with seconds and with am/pm) to match existing options. But I don't think having separate controls for each parameter will be good user experience
