### ISSUE TITLE
Sorting links in tab group

### ISSUE THREAD

**Issue by brucewestfall** [OlegWock/anori#131]
First off, I am SO super picky about technology. Install, dive in, test, adjust, delete is my usual timeline.
Anori is not getting that last step.  VERY nice job on this.

Just a quick maybe todo or perhaps I'm just missing something.  I would like to rearrange the order of links since they seem to open according to that order.  I will probably just go into the export file, copy/paste then use that version.

GUI way to do this?  Like the drag-n-drop rearranging of widgets when editing?

If not, no biggie, just a question.

**Comment by OlegWock** [comment]
Hello Bruce. There is no way to do this in GUI at the moment, I'll consider adding it in next version (no estimate when it will be released though)

**Comment by OlegWock** [comment]
Tried adding this, but library we use for drag-and-drop and reordering seem to glitch heavily when used in configuration modal and I feel that troubleshooting it will take too much time, so I'm going to close this issue as 'won't fix'
