### ISSUE TITLE
Anori has a problem not fitting the screen.

### ISSUE THREAD

**Issue by kiznick** [OlegWock/anori#135]
Before the update, It fit the screen correctly, but now it does not fit anymore
![image](https://github.com/OlegWock/anori/assets/22832362/3b0b5663-7394-41fd-bbe1-500d06d3cd9e)

I found a way to make it fit again
https://github.com/OlegWock/anori/assets/22832362/3cf1f725-15dc-45e3-91b5-d49e5cd1e051

**Comment by OlegWock** [comment]
This should be solved in next version (1.16), so I'm going to close this issue. Let me know if problem still persists after the update
