### ISSUE TITLE
Chrome is blocking page

### ISSUE THREAD

**Issue by cwharts** [OlegWock/anori#136]
After installing the extension, when I try to open a new page, I get this error:

ddeaekifelikgnaacipabpmjpffgifek is blocked
This page has been blocked by Chrome
ERR_BLOCKED_BY_CLIENT

**Comment by OlegWock** [comment]
1. Did this started happening after recent update of Anori or did you just installed it for first time?
1. Any chance your laptop is being managed by your organization? You can check it pasting this address in addressbar `chrome://management`
1. Did you try reinstalling the extension or restarting Chrome?

**Comment by cwharts** [comment]
1. This is my first time using the extension.
2. Personal computer at home
3. Yes, both.

Actually discovered it was another extension was blocking it. Thanks for
your help though.
