### ISSUE TITLE
Open Anori only by clicking in the extension button [Feature Request]

### ISSUE THREAD

**Issue by garcialn** [OlegWock/anori#141]
I loved the Anori extension, but since i'm using Brave (which also has some interesting takes for more productivity which i really like), i really would love to use Anori only by clicking the extension button. Brave has some functions on "new tab" page which works better for me, but there's even more in Anori. But for me to use both tools, i have to toggle on/off the extension to access Brave's functions, which leads me to keep Anori off the majority of the time.
If there was a configuration to use the tool, but not through the "new tab" button, that would be amazing.

**Comment by OlegWock** [comment]
Unfortunately, this isn't possible without creating separate version of Anori. Extensions in browser can't conditionally 'propose' to change new tab. Either they declare it in their manifest and browser will change new tab page or they don't declare it in the manifest and they never can propose to do so.
