### ISSUE TITLE
Group of Favorites [Feature Request]

### ISSUE THREAD

**Issue by garcialn** [OlegWock/anori#142]
I ran into 2 different "problems" when using the "Group of Favorites" widget (which, for me, tends to be the most used one...):
- When configuring the widget, the only way to import links in doing so one by one, which ends up taking way to much time (when there's a "big" list of links to add)
- When opening the group, the only way of opening the links is opening them all at once
---
**Suggestions:**
- Feature to import several links into a group all at once
- Feature to open the links from groups one by one

**Comment by OlegWock** [comment]
This sounds like feature which was requested in #117, I'm going to close this issue. You can subscribe to mentioned issue to get notified about updates

If those are different features please feel free to reopen this issue
