### ISSUE TITLE
Search widget - open results in new tab

### ISSUE THREAD

**Issue by veludoleao** [OlegWock/anori#143]
Thank you for the great extension. Could you add an option in the search widget to show results in a new tab, like we have in the bookmarks widget?

**Comment by OlegWock** [comment]
Hello! I don't think it makes sense to add separate option to **always** open results in new tab. But I altered behavior a bit and now if you Ctrl+click (cmd+click on mac) the search icon or press Ctrl/Cmd+Enter, this will open results in new tab

version 1.16.2. I'll upload it to stores today, but it will take a few more days to get it published
