### ISSUE TITLE
Using Anori on the start of Firefox

### ISSUE THREAD

**Issue by gcorreaxd** [OlegWock/anori#145]
I use Brave and Firefox, and see a different behavior on the startpages.

In Brave, Anori can start without do nothing.
In Firefox, Anori just appears on the New Page, but I need this on the homepage always.

Here: 

![image](https://github.com/OlegWock/anori/assets/93776429/2e13b9ac-5a36-434c-a15e-0f7fd3847850)

And here:

![image](https://github.com/OlegWock/anori/assets/93776429/40dbe941-77c8-4bc8-a036-af7beb62955b)

I think in change some options in about:config , but I not see the "address" to force open Anori

**Comment by OlegWock** [comment]
Hello! This should be fixed in version 1.16.2. I'll upload it to stores today, but it will take a few more days to get it published. After update you might need to select Anori as homepage in Firefox preferences (it might be set automatically after the update, but I'm not sure)

**Comment by gcorreaxd** [comment]
Wooow it's working

I update the extension and do some tests. I thank what it is more fast now too. 
Thank you!
