### ISSUE TITLE
Making the save button a bit more visible

### ISSUE THREAD

**Issue by brucewestfall** [OlegWock/anori#148]
Maybe put the Save button next to the Add button.  On screens like this it is very easy to forget to scroll down.
![Screenshot_2023-12-29_08-30-08](https://github.com/OlegWock/anori/assets/24705459/b2c86f6a-4ed9-4028-9ac1-5bf365e1b941)

For a while i thought something was broken since it never saved my changes.  

The majority of users are smart enough.  Just edit the layout for the clueless minority like me.

**Comment by OlegWock** [comment]
Hello. I understand your struggle, but I think it's too minor use-case to adjust the layout. I'll be closing this issue
