### ISSUE TITLE
Any support for Arc browser?

### ISSUE THREAD

**Issue by pkellner** [OlegWock/anori#149]
Lately, I've switched (mostly) to using Arc as my chromium based browser as it seems much faster and cleaner then the alternatives. It has a different way of adding tabs. Any planned support for that?

BTW, I appreciate your concern and transparency around how you discuss privacy and privilege in extensions. I've written a few extensions myself, and based on that experience, am very very careful around what I install. Almost every useful extension I've found takes ridiculous privileges and no one calls them out on it. I was once in a meeting with the Edge team at Microsoft and I asked sbout the gaping holes, and their response was that very popular extensions would be found out if they did bad things. I don't believe that for a second.

**Comment by OlegWock** [comment]
Hello Peter! I'm very delighted to hear your kind words about Anori's privacy policy :)
Indeed, after working with extensions myself I now do quick audit of every extension I install

As for Arc support, as far as I know they do allow overriding new tab, but it's not used unless you explicitly navigate to `chrome://newtab` (or `arc://newtab`). I believe only option is to pin Anori in extensions toolbar and click its icon to open new tab (same as we recommend for Opera users, where it's impossible to override new tab). Which is still not ideal, but with one of recent updates (where they moved pinned extensions to addressbar) it's at least usable

![CleanShot 2024-01-08 at 10 33 00](https://github.com/OlegWock/anori/assets/7430438/c66d1f57-7d38-4814-aae6-7a019df53d9e)

**Comment by OlegWock** [comment]
I'm going to close this, let me know if you have any other questions or suggestions.
