### ISSUE TITLE
Open search in new tabs

### ISSUE THREAD

**Issue by joseiriarte1982** [OlegWock/anori#150]
Pretty nice for sure, however it be nice that the search could be opened on a new tab because it opens on the same home tab. And the concept is to have the tab available at all times, as a reminder of tasks and quick access to production. I am currently using chromium, and I couldn't find an option to open searchs with duck duck in new tabs. Also a black theme would be nice, I got the gray one to match my mood XD but black is for the eyes, beside the style. Actually by seeing your codebase I figure it out that with meta key and enter one can open in new tab, but it doesn't focus, at least I still don't find how to.

**Comment by OlegWock** [comment]
Hello! If you press Cmd (or ctrl for windows) and click on search icon or press enter search results will open in new tab. New tab won't be focused, this was made to follow behavior of Chrome's own search bar (you can Cmd/Ctrl+Enter there too), and there is no option to change this behavior at the moment. As a workaround you can use Ctrl+Tab (same on mac and windows) to switch to the next tab

**Comment by joseiriarte1982** [comment]
Thank you! I downloaded Vimium because Ctrl+Tab wasn't working neither Windows key+tab, plus I read some notes regarding new tab that allowed me to wrap my mind to the idea that actually new tab is not the same as Home and shouldn't be treated as such but a departing point, and one that feels like home is better of course, that's where Anori's come in. So now I now worried about always keeping at hand my home tab open, cause heck we usually have more than 30 or 40 tabs XD But any way, I find Anori pretty cool, thanks!!

**Comment by OlegWock** [comment]
I'm going to close this now, feel free to reopen or create new issue if you have any issues with Anori :)
