### ISSUE TITLE
Suggestion: Option to have all Anori links open in a new tab

### ISSUE THREAD

**Issue by likelyculprit** [OlegWock/anori#151]
See title. I'd love to have my Anori page always present and ready because my links have opened in a new tab, leaving Anori open.

**Comment by OlegWock** [comment]
Hello! You can open almost any link (besides recently closed tabs) from Anori in new tab with Cmd/Ctrl+Click or click with middle mouse button (depends on your system). For bookmarks you can also select to open them in new tab by-default. 

But I don't think there is need in an app-wide option. I understand your desire to keep Anori open (I do it sometimes too), but Anori was designed to replace new tab with 'speed dial' for important bookmarks/notes/etc, not a dashboard you keep open all the time.
