### ISSUE TITLE
other theme

### ISSUE THREAD

**Issue by frmartens** [OlegWock/anori#154]
Hello,
I read in the german C't about your project and installed it for Mozilla. The themes I do not like - I would prefer simple colors. And how to define the exact size of the windows?

Please help me - Thank you!
Frank

**Comment by OlegWock** [comment]
Hello Frank! It's currently impossible to create your own theme with custom colors, but it's on roadmap, it's tracked here https://github.com/OlegWock/anori/issues/44

This feature is quite involving, but currently I can't spend much time on this project, so there is no estimate available on when it will be added. 

> And how to define the exact size of the windows?

If you mean widgets, some of them (e.g. notes, todo list) can be resized, when in edit mode, those widgets will have a button/handle which you can pull to resize them. Other have fixed size. Size is measured in 'boxes' and rounded to nearest integer, i.e. you can't resize widget to 1.5 boxes. There is no option to set custom box size.

---

I'm going to close this issue, but feel free to reply if you have any other questions or create new issue if you found a bug or would request new feature.
