### ISSUE TITLE
Search bar for “Add widget”

### ISSUE THREAD

**Issue by GrimPixel** [OlegWock/anori#156]
It currently requires mouse scroll several times to reach the end. If they were in tabs, it would be only one mouse-click.

**Comment by OlegWock** [comment]
We might add search to this screen, but I don't think splitting it into tabs is right decision

**Comment by GrimPixel** [comment]
Yes, I agree that a search bar can work better.

**Comment by OlegWock** [comment]
Hello! This should be fixed in version 1.17.0. I'll upload it to stores today, but it will take a few more days to get it published.
