### ISSUE TITLE
Feature Request: Dynamically resizable widgets.

### ISSUE THREAD

**Issue by bagarwa** [OlegWock/anori#16]
Right now, the widget sizes are picked at the start and they stay at that size. For example, If you want the notes widget to be bigger, you have to add a new widget and select the bigger notes widget, copy over all the text from your existing smaller notes widget and then delete that smaller widget. 

Instead, if I can change the widgets' size dynamically, even after adding them to the board - that'd be great. Maybe let me drag the corners of the widgets to resize them.

**Comment by OlegWock** [comment]
Hello! This is technically challenging as everything build around assumption that widgets have fixed size. While I understand why this will be useful, it will just take too much time and it isn't worth it.
