### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by Crampo09** [OlegWock/anori#165]
Hey,
Would it be possible to select where data can be stored / read from, 
i.e. if i selected a folder in a cloud drive. So that if i logged in on another device. 
then i could have the same dashboard on both?

Thanks :)

**Comment by OlegWock** [comment]
Hello @Crampo09, currently this is not possible. There was some discussion in https://github.com/OlegWock/anori/issues/47

But it all boils down to being just too big task for me to work on currently, as I have very limited time I can spend on Anori

I'm going to close this issue in favor of #47, please feel free to post your comments (if you have any) there
