### ISSUE TITLE
Decode HTML entries in RSS widget

### ISSUE THREAD

**Issue by kismaeleg** [OlegWock/anori#168]
When a text has quotation marks, they do not appear. &quot; in your place. Can you fix this?

![53c9](https://github.com/OlegWock/anori/assets/9274203/e448da01-9ec6-4c0e-be0f-f1dfc251ab68)

**Comment by OlegWock** [comment]
This should be fixed in v1.18.0 (you should get this update automatically by this time), so closing this issue
