### ISSUE TITLE
Allow larger icons

### ISSUE THREAD

**Issue by kismaeleg** [OlegWock/anori#170]
In favorites, allow larger icons to replace titles.

**Comment by OlegWock** [comment]
@kismaeleg could you elaborate what you mean by favorites? Bookmarks? Top sites?

**Comment by kismaeleg** [comment]
@OlegWock, in previous updates, what I had asked for was fulfilled.

**Comment by kismaeleg** [comment]
@OlegWock,  in previous updates, what I had asked for was fulfilled.
