### ISSUE TITLE
Bug found and suggestions

### ISSUE THREAD

**Issue by Gediminas-Petraitis** [OlegWock/anori#172]
Hello Oleg,

My name is Gediminas. I'm from Lithuania. I downloaded and installed the latest version of your app (Anori: Productivity New Tab v1.17.0). This extension fundamentally changes the browser's graphics and functionality as it integrates into the core browser code. So, I'm shocked because I found something that other app developers couldn't create. What do I mean by that? I was used MS Explorer before the release of the full-featured version of the Opera browser. I switched to Opera because the Presto search engine was the most stable. Later, Opera switched to the Chromium framework and the Blink search engine, and it was with all this that it partially ruined the browser itself. Later, even more stupidity followed - Opera shares were bought by the Chinese, and this was just a blow to data security. In the end, the Chinese withdrew from the company's shareholders, but the Opera browser itself remained with the Chromium search engine. The last straw that made me look for an alternative to the Opera browser was its latest version - Opera One, a version with AI integration. I thought of looking for an alternative. Out of all the browsers, MS Edge was working best. Although Edge uses the Chromium search engine, Microsoft for some reason integrates an older version of it, and as a result, the speed of the browser is really high. Of course, nothing is perfect, so Edge also has a whole palette of flaws. For example: there is no functional Start page (new tab page), there is no elaborated Speed-dial module, bookmarks management is a total misunderstanding, which has survived from the days of Internet Explorer -  up to the Opera browser bookmarks management function, looks like the evolution of the candle to the level of LED semiconductors. Despite all these shortcomings, Edge itself is faster than Chrome, Opera, Brave and Vivaldi. So, the idea came to mind to do a little Edge tuning. I had looking for best Extension for several days. All the extensions I found are total shit (sorry for the expression). Either all  they are Chinese "creations" or "started but not completed projects". I had already given up hope of finding normal solution. Finally I came across your project - Anori - quite by chance. I downloaded the CRX package. The archive capacity is big as the offline installation file of the Edge browser :D I unpacked it, checked only the content and saw that basically the big "weight" of the application is only due to the libraries of icons. I decided to install it and was surprised when I did. Wow! It's cool!

P.S. sorry for such a long story, but without it you would hardly understand what a unique project you are doing.

So, now I would like to move on to the technical part. I found one bug and have some suggestions. I'll start with the bug:
--------------------------------------------------------------------------------------------------------------------------------------
Lagging is noticeable when launching the browser. The same happens when opening a new TAB or refreshing the browser (Ctrl+F5). Visible preloading of default theme. Video attached

https://github.com/OlegWock/anori/assets/164376244/ae2b3a47-402d-4362-aba3-203605b67650

1. I think this is because the javascript file is too big due to the 8 default themes in it. Very large code and slow him fetching.
2. Browser startup lag can also be affected by libraries of default icons. The occupied amount is very large (size: ~50.3 MB) in location assets/icons.

Solutions:
1. I think that lag can be avoided or at least greatly reduced by giving the user the opportunity to delete (remove) selected one or all default themes. This would not reduce the functionality, and if the user were to stupidly delete the important theme, he could restore it using a backup file (i.e. archive). By the way, removing default themes without making a backup first is the same as trying to format the system disk... As i like to say - there no cure for stupidity :D

2. About the icons... I'd be inclined to think that there's really no need for so many and so many more icons. There was a time when we built "computers" on the Z80 processor platform, so we could only dream of colored icons. Later, colored icons became fashionable in ICQ, Mirc and similar software. Now, those Easter Eggs are used only by the Chinese and Vietnamese. Everyone is moving towards minimalism and aesthetics. Even Microsoft copied their OS Windows 11 and app design from KDE as I like to say :D So, I would recommend removing the following icon libraries:

Fluent Emoji Flat
Twiter Emoji
Flat Color Icons
VScode Icons

Recommendations for improving design and functionality.
----------------------------------------------------------------
1. Speed Dials. Missing additional information ("Description") on Speed dial's. Font size of "Title" is big (h2) and very bold. Font size of "Description" should be less than size of "Title" but large than "URL". Also, font style of "Description" should be lightweight (looks better). Missing option to add and remove  the "Speed dial" button by using context menu (right-click), without entering into main editing mode. I think that this feature can be integrated, because Edge is indeed based on the Chromium open-source project. If we were talking about integration into the Win OS itself, then it would not be worth wasting time. 

![img_1 1](https://github.com/OlegWock/anori/assets/164376244/2e162584-e010-4366-8196-7d9a8c75a1a0)
![img_1 2](https://github.com/OlegWock/anori/assets/164376244/bafb51fc-8f4c-4ab0-bb03-39e999bca51e)
![img_3 1](https://github.com/OlegWock/anori/assets/164376244/d004d92c-696f-4743-817c-5b5ce58bc34f)
![img_3 2](https://github.com/OlegWock/anori/assets/164376244/91000718-9c76-49e0-8106-0f3ba24a7dea)
![img_3 3](https://github.com/OlegWock/anori/assets/164376244/b3a73062-7f39-4263-a315-6076a329cf58)
![img_3 4](https://github.com/OlegWock/anori/assets/164376244/b279d774-b73e-4917-b787-0a08509b12c6)

2. Rounded corners. All corners main and modal windows are very rounded. Radius too large.

![img_2 1](https://github.com/OlegWock/anori/assets/164376244/47662404-ebd1-473f-ab1c-0796381d3b2c)
![img_2 2](https://github.com/OlegWock/anori/assets/164376244/519f10ef-d0a2-4ab6-8f40-fb9bae60af20)
![img_2 3](https://github.com/OlegWock/anori/assets/164376244/afa6147d-374e-4722-b6c3-4e9f5480eac9)

3. List of "Customer Icons". The size of the icons is very small. It is difficult to see and find the required icon if there are several with similar colors or designs. The width of the modal can be larger and the quantity of icon columns smaller. Then the icons would become bigger and more visible.

![img_4 1](https://github.com/OlegWock/anori/assets/164376244/7a13628d-a1da-41b5-831e-94e4883969f5)
![img_4 2](https://github.com/OlegWock/anori/assets/164376244/8074d5b7-f8e1-4944-8542-5347d34d5877)

4. Folders. The name "Folders" sounds somewhat unusual. Of course, this does not change the functionality, but the name itself is associated with docx, xlxs, txt or DWG file folders. "Spaces" would look nicer and more understandable. "Work spaces" would look more solid, but the two-word term takes up a lot of space in the HTML, and is already used in other programs. The name "Spaces" would seem like some kind of unique, exclusive and "infinite" User environment. Well, this is just my take on it... 

![img_5 1](https://github.com/OlegWock/anori/assets/164376244/822ef984-a10b-4b34-bb21-58ea6295e926)
![img_5 2](https://github.com/OlegWock/anori/assets/164376244/66d5b7b6-dbee-468b-bd8c-a122ed4889c6)

5. Theme selection and options. Very uninformative settings modal window. Color setting buttons like Russian roulette - "press and try to guess" (no <div> labels). 

![img_6 1](https://github.com/OlegWock/anori/assets/164376244/a2034df0-868a-4d99-acd6-c82ccf5d3bbf)

These this application improvements, like every ВАЗ ЗАЗ or Москвич, putting rain rims on them will not really turn Ferrari into a racing car, but they will make browsers more convenient and more, if in the future you develop the Bookmarks module, this yours application will become extremally popular. Maybe more popular than the browsers themselves. Also, if you are interested, I can help with the integration of the Lithuanian language.

You can contact me directly by email. by mail: gediminas.petraitis@hotmail.com
If you want, you can also write in Russian.

Best regards & Слава Україні!
Gediminas

**Comment by OlegWock** [comment]
Hello Gediminas, thanks for your kind words. 

Regarding lag on tab open, you're partially right. Delay is noticeable because of JavaScript bundle is quite big, but I believe I optimized it almost to the limit. There is no much more of stuff I can move to be "lazy loaded" later, a lot of code is required to render all the widgets. Other themes don't take much space actually, as their files not loaded unless user set this theme. Second cause is how custom theme works. Browser extension have limited capabilities for storing files (pictures in this case), we can only use OPFS to save picture and then use JS to load it from there and set it as background, we can't embed it directly in HTML file so it will be preloaded (like we currently have with built-in green theme). So there is noticeable delay between tab open and moment when JS is able to change background. This probably can be optimized a bit more, I hadn't much time to look onto it after release of custom theme, but I'm afraid there still will be blinking, just shorter.

Re removing some icons. They are used by other users (including me) and were part of Anori from the very first (public) versions. They affect bundle size, true, but in my tests I didn't found any negative effects of browser performance, so I'm inclined to keep them.

Thanks for your design suggestions, I'll keep them in minds when I get more time to spend on Anori. But I'm quite authoritarian when it comes to design, so I can't guarantee they will be implemented.
