### ISSUE TITLE
There should be an option to show the bookmark bar in a new tab.

### ISSUE THREAD

**Issue by azadshaikh** [OlegWock/anori#18]
There should be an option to show the bookmark bar in a new tab.

**Comment by OlegWock** [comment]
Hello @azadshaikh. While I understand the the value this will bring to the extension, I don't see how this can be implemented to be convenient and good looking at the same time. Especially on firefox, as there are additional limitations. I'm not dismissing the idea completely, but this isn't something I'll add in nearest future.

Thanks for your feedback
