### ISSUE TITLE
"onboarding" never started

### ISSUE THREAD

**Issue by kimusan** [OlegWock/anori#185]
I have installed this extension on Chrome (win10) and after I say "keep change" after installation, I just get a green background. 
The "onboarding" never starts and I have no way of configuring the look of this. 
I have restarted chrome, reinstalled the extension and all sorts of other variations of this - no luck. 

Is there a way to trigger the onboarding or get to the configuration in another way ?

**Comment by OlegWock** [comment]
Hello! By 'green background' you mean solid color or do you see a blurred photo?

Could you open the console (Right click on page > Inspect > Console tab) and send me a screenshot of it? If there is a lot of logs, please check if there are any errors and send screenshots of those too.

**Comment by kimusan** [comment]
It was a solid green and no errors or anything in the console. I did a reinstall once more and this time I suddenly got the onboarding to show up, so it seemed to have been some install glitch
