### ISSUE TITLE
Request: Sync and Coda icon

### ISSUE THREAD

**Issue by KevanMacGee** [OlegWock/anori#186]
Great extension! I have it on 2 PCs.

Two things I would like to request:

- Could we have an icon for the notetaking/collaboration app Coda? 

- As I mentioned, I have this on 2 PCs and I'd like to have a way to keep changes to each in sync. Right now, I just export the settings on one browser, save it to a Mega folder, it gets synced to the other PC and then I import it on that PC. I don't know if this could be automated through Mega or another provider. I'm also not sure if this could be handled in the browser sync feature. I personally use Brave and while the Brave sync does sync the extension itself to other PCs I'm signed in to, it does not sync the settings of any of the extensions. (Sorry for the novel)

Again, great work and thanks for adding ease to my life!

**Comment by OlegWock** [comment]
Hello, thanks! 

> Could we have an icon for the notetaking/collaboration app Coda?

You can add your custom icons in settings and use them in all places where you can use normal icons. Anori uses icon packs made by third party (https://iconify.design/), so we don't manage available icons ourselves. 

> Sync

This was requested before and currently I close all requests in favor of this one #47 (just to keep things tidy). Unfortunately, browser's built-in sync mechanisms doesn't fulfil Anori's requirements, so adding sync will require making our own solution. This is time consuming task and I don't have time to tackle it currently. So while cloud sync is definitely on roadmap, there is no ETA when it will be added.

I'm going to close this issue, but feel free to reply if you have other questions.
