### ISSUE TITLE
Hide sidebar when only single folder is used

### ISSUE THREAD

**Issue by moookino** [OlegWock/anori#192]
Hi @OlegWock 

Is it possible to add option to hide sidebar when only single folder is used or have hide sidebar feature in general?

**Comment by OlegWock** [comment]
Hm, that makes sense. But with this change, settings menu will become unavailable too. Maybe better idea will be to have opt-in to hide sidebar by default and show when user moves mouse to left edge of screen 🤔 

I'll think about it

**Comment by moookino** [comment]
maybe you can have hiding as an option under extension on firefox extension page and general as well. Since you already have shortcuts implemented it'd be easy for any experienced user to just update general settings with opt+s or alt+s if needed and for new user they always can find that option on extension page. So it could possibly simplify implementation

**Comment by m-p-3** [comment]
May I add the ability to scroll the sidebar too? I made a fair amount of folders on my 4k monitor while docked and I couldn't see them all when I switched to my laptop screen without zooming out so I could access them all.

**Comment by OlegWock** [comment]
Tbh, I didn't expected anyone to make that much folders 😁
I'll add scroll in next release (hopefully next week/early in June)

**Comment by OlegWock** [comment]
Just pushed v1.19.0 to stores, this version includes option to auto hide sidebar (Settings > General) and now if you got a lot of folders, sidebar will be scrollable. So I'm going to close this issue, but if you have any issues with new features let me know (it will take a few days for Chrome/Firefox store to review the update)
