### ISSUE TITLE
Resource intensive. Slows down the browser, including typing.

### ISSUE THREAD

**Issue by bagarwa** [OlegWock/anori#20]
Whenever I open a new tab and the Anori page loads, the browser becomes very slow. Even the typing gets slow when I type any url in omnibar at this point. When the actual website loads or when I switch to any other open tab, things go back to normal. 

Windows 11 22H2 (22621.1485)
Chrome 113.0.5672.24 (Official Build) beta (64-bit)
Anori 1.3.0

**Comment by OlegWock** [comment]
Hello @bagarwa. Thank you for your interest in project. From this info I can't really see or reproduce what causes this behavior. If you could provide performance profile that will help.

To obtain this profile, open new tab with Anori, open DevTools (CTRL + SHIFT + I on Windows), switch to Performance tab, hit 'Reload and record' button. If slow down occurs after certain action, reproduce it now. After slow down was present for some time (10-20 seconds should be enough), click on stop record and then on 'export' button. This will save a file which you'll need to upload here so I can take a look and check what causes troubles with performance.

While this file shouldn't contain any private info, if you're not feeling comfortable sharing it publicly here, you can send it to my email: oleh@sinja.io

**Comment by jacek-jablonski** [comment]
Hi, I can confirm above problem. Every time I leave anori open on new tab, my computer's fan starts to blow with full speed. I'm attaching my profile.
[Profile-20230418T085519..json.zip](https://github.com/OlegWock/anori/files/11258821/Profile-20230418T085519.json.zip)

**Comment by OlegWock** [comment]
Thanks @jacek-jablonski, that helped a lot. Could you remove 'Top sites' widget and see if issue is still present?

**Comment by jacek-jablonski** [comment]
Removing 'Top sites' widget solved the issue for me 👍🏻

**Comment by OlegWock** [comment]
This issue fixed in version `1.4.1`. I submitted it to Google & Mozilla, but it might take up to a few days to be published. Once it published, Chrome/Firefox will automatically update your extension.

Feel free to re-open (or create new issue) if problem is still present in v1.4.1
