### ISSUE TITLE
🌱 Suggestion — Dynamic Sizing

### ISSUE THREAD

**Issue by 8227846265** [OlegWock/anori#200]
I have two monitors with different display sizes, and I can't get Anori to display the widgets in the same size layout. It would be great if the widgets resized accordingly to maintain the same layout.

Monitor 1:
![image](https://github.com/OlegWock/anori/assets/66582769/9700d679-ed90-404c-9984-0559b34bcd55)

Monitor 2:
![image](https://github.com/OlegWock/anori/assets/66582769/771dab0d-f2e3-409e-86bd-e71a75f8be90)

**Comment by OlegWock** [comment]
This is intended behavior. As a possible workaround, you can enable 'Automatic compact mode' for monitors with width smaller than X, so on you smaller monitor Anori will go in compact mode

**Comment by 8227846265** [comment]
> This is intended behavior. As a possible workaround, you can enable 'Automatic compact mode' for monitors with width smaller than X, so on you smaller monitor Anori will go in compact mode

Is there an option to maintain a consistent layout across different monitors? This is important, especially for individuals with OCD, as they prefer uniformity in their layouts on all screens.

One possible implementation could be:
- Adjust the size of the blocks and font on the secondary monitors to match the primary monitor's layout, scaling them up or down as needed.

**Comment by OlegWock** [comment]
Layout is always consistent in that sense that widgets don't jump to new places. But since pixel density and the space available will be different on different monitors, it might look different. Anori widgets are made with assumption that each square will have certain size and re-doing all widgets to support different system isn't worth it

**Comment by 8227846265** [comment]
> Layout is always consistent in that sense that widgets don't jump to new places. But since pixel density and the space available will be different on different monitors, it might look different. Anori widgets are made with assumption that each square will have certain size and re-doing all widgets to support different system isn't worth it

I understand. I guess I just need to get used to it.
