### ISSUE TITLE
support new tab for search?

### ISSUE THREAD

**Issue by xlsqac** [OlegWock/anori#207]
support new tab for search?

**Comment by OlegWock** [comment]
I don't understand what you mean

**Comment by xlsqac** [comment]
![image](https://github.com/user-attachments/assets/6f21099a-e5c5-4fa6-ad0a-0459a543d221)
Open in a new tab for search

**Comment by OlegWock** [comment]
If you press Cmd (Ctrl on Windows) and press Enter OR click search icon with Cmd/Ctrl pressed, it should open search results in new tab. But there is no plans to add an option to always open results in new tab

**Comment by xlsqac** [comment]
ok. thanks
