### ISSUE TITLE
Customizable Icon ?

### ISSUE THREAD

**Issue by AguilaDesign** [OlegWock/anori#21]
First of all, very nice work, it is rare to find tab page extensions that are qualitative, beautiful but especially that works locally !

I was wondering, is it planned to allow the addition of custom or local icon for bookmarks (SVG or PNG) ?
I wanted to find a solution by looking at the code but I never used TypeScript.

**Comment by OlegWock** [comment]
Hello @AguilaDesign. I'm glad you liked Anori.

Tbh, this is something I myself was thinking about and I'm sure it will be good to have. I'm not sure how to exactly implement this (yet), but this definitely will be added (sooner or later, as I don't have much free time for this project these days)

**Comment by AguilaDesign** [comment]
Glad to see you share this idea 😁. From what I understand, you're using the Iconify API with a "select" list of icon families. I imagine that implementing this would change a lot of things. 
If you want to keep the same system, you could use (for the default icon) an API like https://faviconkit.com/. This would allow you to get the Favicon of the site without any extra step. 
I don't know if it's easier or more complicated, I leave the idea here just in case. 

Anyway, it's always a pleasure to see such open source projects, designers should be inspired a little more by developers and the world would be so much more beautiful.

**Comment by OlegWock** [comment]
Support for custom icons landed in v1.5.0. It might take a few days for Google/Mozilla to rollout this update to users. Feel free to reopen/create new issue if something doesn't work.

**Comment by AguilaDesign** [comment]
Indeed the update on Firefox took a few days but the integration is great, what a speed of execution! 

I only encountered a problem with SVGs when uploading everything works but when I close the page and open another one all SVGs become unavailable. This problem does not exist for PNG and JPG (I did not test the GIF). 

In any case, thank you very much!

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
