### ISSUE TITLE
New Tab Focus Issue on Firefox

### ISSUE THREAD

**Issue by jarz76** [OlegWock/anori#219]
I'm having a small issue that slightly disrupts my experience with the extension. When I open a new tab using right-click > 'New Tab,' the focus doesn't go to the address bar. But if I use the '+' button, it works fine.

I checked the repo for similar issues and found some related to Chrome, caused by the 'Focus Stealer', but I couldn't find this option in Firefox.

Here are videos showing the issue:
When opening a new tab using right-click

https://github.com/user-attachments/assets/6050397a-4ee0-416e-b278-df6322b8e040

When creating a new tab using the '+' button

https://github.com/user-attachments/assets/4accfab7-916f-4545-b596-ff7134a205bb

Aside from that, I love the extension and the customization options. Thank you!

**Comment by OlegWock** [comment]
Hey @jarz76. I don't think it's related to Anori. It doesn't have a way to know if you open it one way or another to even somehow react to that. Could you try if using any other new tab extension produces same results?

**Comment by jarz76** [comment]
> Hey @jarz76. I don't think it's related to Anori. It doesn't have a way to know if you open it one way or another to even somehow react to that. Could you try if using any other new tab extension produces same results?

Ah, you're right. I just tried several extensions, and they produce the same issues. It's my first time using this kind of extension, I love it, but now I found this out...

So, the issues might be on the Firefox end? Everything works normally when I'm using Firefox default home.
