### ISSUE TITLE
Can't grant permissions with Kiwi browser.

### ISSUE THREAD

**Issue by mikhoul** [OlegWock/anori#22]
The button is there but when I click on nothing happen and permissions  are not granted.

https://github.com/kiwibrowser

**Comment by OlegWock** [comment]
Hello @mikhoul. It seems to be rather problem with Kiwi browser than extension. I'm not sure it it supports runtime permissions at all, when I tried it just crashed browser

**Comment by mikhoul** [comment]
Your right, but in the meantime that the issue will be fixed could you make a version of the extension that already have all the needed permissions ?

**Comment by OlegWock** [comment]
Yeah, this should work. I'll give it a try tomorrow

**Comment by mikhoul** [comment]
Thanks !

**Comment by OlegWock** [comment]
[Anori-chrome-all-permissions-production-v1.5.1.zip](https://github.com/OlegWock/anori/files/11303069/Anori-chrome-all-permissions-production-v1.5.1.zip)

Here you go. You can install this in Kiwi browser. I quickly checked and permissions seems to work now. And I also fixed a few critical issues (drag-and-drop didn't worked, settings button wasn't visible). There are still a lot of minor issues with layout, but at least it's usable now.

**Comment by mikhoul** [comment]
Thanks a lot I will try it tonight with Kiwi. ! :octocat:
