### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by DasFlogetier** [OlegWock/anori#23]
The best thing would be an option to do a custom widget where you can tinker around with the help of CSS.
And if you could create your own themes with background images and color settings.
Maybe also the option to resize widget how you want it to be in a sort of gridview?

**Comment by OlegWock** [comment]
Hello @DasFlogetier! Thanks for your review in Chrome store :) Could you elaborate what you mean by

> an option to do a custom widget where you can tinker around with the help of CSS

Do you mean something like userstyles? I.e. ability to add your CSS which is applied globally?

> Maybe also the option to resize widget how you want it to be in a sort of gridview?

This was requested a few times already, but at the moment I think it will be too much work, so it's not a priority, but I'll keep this in mind, I think eventually this will be a good feature to have

**Comment by mileshc1** [comment]
Can I request another feature where you can sign in and save the layout so you can sync across multiple devices. 
Thanks and love what you have so far.

**Comment by OlegWock** [comment]
I'm closing this as inactive. Feel free to reply and we'll reopen this
