### ISSUE TITLE
Anori Chrome extension slow and laggy.

### ISSUE THREAD

**Issue by ashleysivana** [OlegWock/anori#25]
When I installed anori chrome extension it was very slow and laggy. Here are the steps I've tried so far:

1. Checked if my browser and mac OS system is up to date. Both are on the latest versions.
2. Tried disabling other extensions that might've interfered. No effect.
3. Cleared cache and browsing data. Still no effect.

My Chrome browser is Version 112.0.5615.137 (Official Build) (arm64).
My Mac OS M1 air is Mac OS Ventura 13.3.1 (22E261).

Hope it gets resolved. I really want to try running this extension on my chrome as I think it would greatly help with my productivity. I am currently a student and honestly know nothing yet of coding etc., just followed the instructions that Chat GPT had given me. Thanks a lot!

**Comment by OlegWock** [comment]
Hello @ashleysivana. Don't worry, your message is fine. Could you clarify does other sites work well on your laptop and do you use it on battery or connected to charger?

**Comment by OlegWock** [comment]
@jdnielss to better understand what causes those issues, could you record performance profile and upload it here?

Here is instructions how to make it: https://github.com/OlegWock/anori/issues/20#issuecomment-1510390466

**Comment by jdnielss** [comment]
@OlegWock here is the file, it might help. I can't upload to GitHub directly, when I upload there is a file type validation. [fileio](https://file.io/5HtpzrJtlCT6)

**Comment by OlegWock** [comment]
Thanks, I'll take a look on this

**Comment by anhtt2211** [comment]
Hi @OlegWock, I have same issue with @jdnielss and I think same performance lol
Hope you will be resolve this issue as soon
Thanks a lot

**Comment by OlegWock** [comment]
Hey folks @jdnielss @anhtt2211 could you check which version of extension you have/had installed?

**Comment by ashleysivana** [comment]
@OlegWock Hi, to reply other sites do work well on my laptop and the extension is still laggy even when it's connected to power or not.

**Comment by OlegWock** [comment]
Hey folks, I put small fix in last version which might fix performance problem. Could someone of you try the new version and see if issue is still present?
