### ISSUE TITLE
opera gx doesnt open the new tab for edit

### ISSUE THREAD

**Issue by mirlafl** [OlegWock/anori#26]
pardon my gramma, my english is barely in the intermediary level.
so i actually installed but the tab to edit the home page didnt appear, and i tried to search the opera settings to see if something was blocking and i didint find anything.
i really appreciate any help.

**Comment by Beather-4D** [comment]
Hello, same issue here

**Comment by sanmartinezf7y** [comment]
hey! same here, tried switching to regular opera but still it doesn't work :(

**Comment by OlegWock** [comment]
It seems that Opera doesn't really allow extension to change new tab. Sorry, folks, I assumed that if Opera based on Chrome it will work the same, so I didn't tested it. 

I'll put a workaround (probably the similar as [Momentum](https://get.momentumdash.help/hc/en-us/articles/4407091791127-Opera-version-) does) for this the next version and will update welcome page.

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
