### ISSUE TITLE
Allow removing sites from top sites widget only in edit mode

### ISSUE THREAD

**Issue by moeyad7** [OlegWock/anori#27]
I think it would be great to have a similar widget as the top sites widget but it has the option to add websites to it and maybe an icon above that shows device battery if possible

**Comment by moeyad7** [comment]
I also think that it would be able to add websites to the top sites widget as I accidentally removed one of the websites and I couldn't add it back or maybe you can put the remove option in the edit section only

**Comment by OlegWock** [comment]
Hello @moeyad7. Thanks for feedback, it's really helpful.

To add your own websites you can use 'bookmark' widget

**Comment by OlegWock** [comment]
I'll keep this open for me as a reminder :) While I don't intend to change the top sites widget, I plan to implement these parts

> icon above that shows device battery if possible
> put the remove option in the edit section only

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
