### ISSUE TITLE
Autofocus new task in ToDo widget

### ISSUE THREAD

**Issue by DinkoAbdic** [OlegWock/anori#28]
1. It would be great if there was a widget for Google Calendar (that would display appointments and other stuff). --> #45 
2. On the ToDo widget - Once you click on + to add a new item, activate the type on the next item and enable writing right away, (right now you have to click with your mouse to get to the item and then start writing), also if you hit "Enter" after finishing an item, automatically create a new item below and enable writing. This would speed things up.

**Comment by OlegWock** [comment]
I created separate issue for tracking google calendar integration. If you wish to get notifications about progress on it you can click 'Subscribe' in right column there https://github.com/OlegWock/anori/issues/45

I'll change this issue to be only about ToDo widget

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
