### ISSUE TITLE
Vivaldi Onboarding

### ISSUE THREAD

**Issue by jeisaacs** [OlegWock/anori#29]
Hi there,

I have just installed Anori after seeing it on TikTok on [Vivaldi](https://vivaldi.com) - a browser that is built on Chrome and accepts all Chrome extensions.

However, despite the extension installing correctly, I don't get the onboarding screen when I create a new tab or open the browser from new.

Please help!

**Comment by OlegWock** [comment]
Hello! In Vivaldi settings search for 'new tab' and check this checkbox. That should help

![image](https://user-images.githubusercontent.com/7430438/233938997-78adb14e-7e83-458d-8cf0-ca05bbac17c7.png)

I'll update welcome page in next version

**Comment by jeisaacs** [comment]
Spot on - that works for me 🥳
