### ISSUE TITLE
Problems with positioning/fitting widgets in grid

### ISSUE THREAD

**Issue by gre36** [OlegWock/anori#30]
I would like to report an issue with the Top sites - horizontal widget. Everytime i try to use it, a window pops-out saying "Can't fit element in grid, sorry" even when the page is empty. I hope you can quickly solve this, thank you.
By the way everything else works perfectly and i love this google extension!

**Comment by OlegWock** [comment]
Hello @gre36! Thanks for report, could you share screenshot of your screen with some widgets added (I need this to see how big they are there and if it need size adjustments in next versions)?

**Comment by jexscx** [comment]
I have the same problem occuring on Chrome. Its the horizontal weather widget and the horizontal last opened top sites widget where this problem takes place.
![image](https://user-images.githubusercontent.com/43171949/233980828-a09bc845-1c84-4584-b7da-d81131d15fa8.png)

**Comment by gre36** [comment]
Here it is:
![widgets](https://user-images.githubusercontent.com/100850038/234001494-be8f537e-75c7-476b-8be0-e35cdb98ecdc.png)
![widget issue](https://user-images.githubusercontent.com/100850038/234001513-9f6f1067-a48a-491d-ba2a-aaf75484d12e.png)

**Comment by OlegWock** [comment]
Thanks! I'll check this

**Comment by OlegWock** [comment]
I changed widget placing code in v1.11.0, so this shouldn't be a problem anymore. Feel free to comment/reopen if problem still persists
