### ISSUE TITLE
Permission button won't work 

### ISSUE THREAD

**Issue by Olexandr1904** [OlegWock/anori#31]
Hey guys. When I'm pressing the Permission button on the top sites widget it's do nothing. 
My Chrome version is - Version 100.0.4896.75 (Official Build) (arm64)
My laptop is MacBook pro with m1 chipset
Do you need some additional info to investigate this?

**Comment by OlegWock** [comment]
Hello! Do you have any errors in console after you click button? (Cmd+Option+J to open console)

**Comment by Olexandr1904** [comment]
Uncaught (in promise) Error: 'favicon' is not a recognized permission.
    at other.js:34:12993

**Comment by OlegWock** [comment]
Oh, I see. If you can update your chrome (to at least 104+) that should solve the issue. It seems `favicon` permission introduced only in recent version of Chrome

**Comment by OlegWock** [comment]
I'll need to update minimal version requirements for extension too

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
