### ISSUE TITLE
Steal focus won't work

### ISSUE THREAD

**Issue by Olexandr1904** [OlegWock/anori#32]
When I choose this option and open a new tab there is no focus on any field.
address on this tab is: chrome-extension://ddeaekifelikgnaacipabpmjpffgifek/pages/newtab/start.html?focused
My Chrome version is - Version 100.0.4896.75 (Official Build) (arm64)
My laptop is MacBook pro with m1 chipset
Do you need some additional info to investigate this?
btw thanks for a great extension and Слава Україні!

**Comment by OlegWock** [comment]
Героям слава :) 

When you open new tab (with focus stealer enabled) and press Cmd+K right away, does command menu opens or nothing happens?

**Comment by Olexandr1904** [comment]
enter command opened

**Comment by OlegWock** [comment]
Then it works as expected. This option just moves focus from address bar to page on open, so you can use shortcuts right away. It shouldn't focus on any particular fields

**Comment by Olexandr1904** [comment]
oh ok, I thought it should focus on the search widget.
