### ISSUE TITLE
Changes to ToDo widget (strikethrough, reorder)

### ISSUE THREAD

**Issue by apushrestha** [OlegWock/anori#33]
Hey, 

Is it possible 
- To create a strikethrough for daily to do when we select the check box instead of deleting the task?
- To be able to move and sort the tasks based on priority
- To be able to color code the tasks (optional)

Thanks

**Comment by OlegWock** [comment]
Hello @apushrestha. Color coding probably won't happen, as extension has quite mono-color design and I'm not sure how colored tasks can fit in it.

> To create a strikethrough for daily to do when we select the check box instead of deleting the task?

Could you elaborate what you mean? Don't delete task right away, but add strikethrough and delete it at the end of day?

**Comment by OlegWock** [comment]
I'm closing this as inactive. Feel free to reply and we'll reopen this
