### ISSUE TITLE
Bookmark Bar Import

### ISSUE THREAD

**Issue by InfinitGit** [OlegWock/anori#35]
I usually use chrome with the bookmarks bar hidden, and in the normal chrome new tab page it automatically shows the bar. If you could add an option to either bring those bookmarks into a widget, or automatically open the bookmarks bar (ctrl+shift+B) and then re-hide it when something is clicked that would be great!

**Comment by OlegWock** [comment]
Hello! Unfortunately there is now way for extension to show/hide bookmarks bar. I'm considering either adding widget which will display bookmarks saved in browser (opposed to bookmarks added to extension). Or maybe adding button to select bookmarks from browser when you create new bookmark in extension

**Comment by InfinitGit** [comment]
Yesss, I see the option to import a single bookmark which is great!
Though for those of us who have a lot of bookmarks in the bar, a widget that allows you to import many at once or just show the ones in the bookmarks bar would be awesome!

Maybe you can make it so that the user adds the desired bookmarks to a folder called Anori or something and then a widget can show just those bookmarks? Or a checkbox system to add multiple at once.


Thanks for your work!

**Comment by OlegWock** [comment]
Hello! This took long time, but it's finally implemented in version 1.10.0. I just submitted it to stores, so it probably will take a few more days to be published. After that your browser will automatically update it and you will be able to enable bookmarks bar in extension's settings
