### ISSUE TITLE
Using favicon as icon for bookmark

### ISSUE THREAD

**Issue by InfinitGit** [OlegWock/anori#36]
It would be great if when a site is left with no logo on the bookmark widget, the little icon from the site is loaded in instead (the little logo that shows at the top of the tab when a site is opened). This is how other new tab extensions work generally to get a logo.

**Comment by OlegWock** [comment]
(Note to myself)

Probably the best solutions will be to use `favicon` API on Chrome and use [faviconkit.com](https://faviconkit.com) as fallback for Firefox/Safari 🤔

**Comment by OlegWock** [comment]
I played with this a bit and it looks ugly :/ 
Most of sites doesn't have icons in big enough resolution to look good. And then there are issues with both `favicon` API in chrome and [faviconkit.com](https://faviconkit.com/) service. I'm going to close this issue. Maybe in future we'll add this feature, but not with current state of things
