### ISSUE TITLE
Translating Anori into your language

### ISSUE THREAD

**Issue by fromerito** [OlegWock/anori#37]
Hi guys. I would like to help you out with English-Spanish translation. Just let me know how can we work out.

**Comment by berndviehboeck** [comment]
I could help with German translation :)

**Comment by OlegWock** [comment]
Hello! That's so cool, thanks! I'll need to do some work before extension can be translated (basically moving all text to separate file). But I'll let you know when I finish

**Comment by TheSnowfield** [comment]
Looking forward to it. I can help with zhCN and zhTW translations :)

**Comment by OlegWock** [comment]
Phew, finally I finished with this. I hope your proposals are still active folks. I prepared all the files and now need you help with translation. I'm not sure if you familiar with translating software, so let me give you a quick intro.

All strings which need to be translated extracted in separate JSON file. You can find them [here](https://github.com/OlegWock/anori/tree/master/src/translations): `de.json` for German, `es.json` from Spanish, etc. They look like this (it's just text file, you can use your favorite text editor or maybe some online tools):

```json
{
    "translation": {
        "noResults": "No results",
        "example": "Example",
        "weekday0": "Monday",
        "weekday1": "Tuesday",
        "settings": {
            "aboutHelp": {
                "title": "Help & about the extension",
                "p3": "Follow author on <0>Twitter</0> and <1>support Ukraine</1>."
            }
        },
        "search-plugin": {
            "name": "Internet search",
            "searchProviderForQ": "Search {{provider}} for «{{query}}»"
        },
    }
}
```

You need to translate only right part after `:`, left part is ID and it should stay same for all translation files. So, for example, here you need to translate `Monday` to your language, but you shouldn't change `weekday0`. 

In some strings you might notice text like this: `{{provider}}` this is placeholder, which will be replaced with actual value. You don't need to translate word inside brackets. However, you will need to place it in sentence where it will look natural. So if we're translating `searchProviderForQ` into Spanish, it should be something like `Buscar {{provider}} para «{{query}}»` I guess.

And there is also constructions like `<0 />` and `<1>some text<1/>`. This is used to embed something more complex than just string (like in previous example). For example, link tag `a`. If there is a text between `<0>` and `<0/>`  you need to translate it (in example with link it will be link's text). If it's just `<0 />` you need just to move it to appropriate place in sentence (this is currently only used for shortcut hints). So if we're translating `p3` into Spanish, it should be something like `Sigue al autor en <0>Twitter</0> y <1>admite Ucrania</1>.` I guess.

If you know how to work with git you can make pull request with your  translation. If you don't know how to work with git you can send translated file to me here and I'll put it into extension.

Thank you!

**Comment by OlegWock** [comment]
And if someone want to translate extension into French (or any other language really), you're welcome :)

**Comment by fromerito** [comment]
Glad you could make it so we can start translating. Count on me with spanish. Im on it.

**Comment by TheSnowfield** [comment]
> but I guess it's generic name for Chinese? Could you help me with this?

I feel so sorry for the late reply, 
Chinese Simplified is "中文 (简体)" or "简体中文"
Chinese Traditional is "中文 (繁體)" or "繁體中文"

**Comment by TheSnowfield** [comment]
I preparing to fork and working on Chinese translations which can take several days. I'm pretty busy these days.

**Comment by OlegWock** [comment]
No problem! Thanks for your help!

**Comment by ichikurosaki** [comment]
Hello 
I can help and translate to Georgian if u want

**Comment by Pannenkoek02** [comment]
Hey, I can translate to dutch, but how do I do that? I don't see a folder with 'Nl'... Do you I need to make one? If so how? (Sorry im new to github i litteraly made an account to translate lmao)

**Comment by OlegWock** [comment]
Hello folks, you can just make a copy of `en.json` file, rename it to `nl.json` or `ka.json` (for Georgian) and translate strings in it 🙂

**Comment by ichikurosaki** [comment]
> Hello folks, you can just make a copy of `en.json` file, rename it to `nl.json` or `ka.json` (for Georgian) and translate strings in it 🙂
on it

**Comment by OlegWock** [comment]
I created a new issue for all translation-related questions/discussion (so I can put actual info in first message in thread and it will be easier to find). I'm going to close this issue, if you have any questions regarding translation feel free to post a comment in #104 

And thank you again for your help :) 
It's so amazing that Anori is translated in so many languages now
