### ISSUE TITLE
I have deleted all the sites from "top sites" and I don't know how to put them back

### ISSUE THREAD

**Issue by georgix09** [OlegWock/anori#38]
Hi! First time using this extension and it is awesome, but unfortunately, I wanted to replace the Top Sites with some other links. I thought it was going to be a "+" button at the end of all sites, but now the space is empty and I don't know how to add the sites back. A bit of help would be very much appreciated. Thank you and keep up with this amazing job!

**Comment by OlegWock** [comment]
Hello @georgix09. Unfortunately there is now way (at least currently) to bring those back 😅

To add your own links you can use bookmark widget

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. You'll need to remove widget and add it again and sites will be back. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
