### ISSUE TITLE
Open New Tab and place cursor into URL bar

### ISSUE THREAD

**Issue by wedevafrica** [OlegWock/anori#41]
Lovely extension. My clumsy brain needs a moment to adjust to this but better than working with the normal Google Tab folders. Just something I wanted to suggest, not sure how to do this. Usually when I open a new tab in Google Chrome to cursor is directly in the search bar/url bar of GC. But with this extension I found myself typing like an idiot just to find out nothing was written. Not sure how this can be implemented?

**Comment by OlegWock** [comment]
@wedevafrica could you check if you have 'focus stealer' enabled in Anori settings?

By default you get same behavior as with normal new tab (i.e. address bar should be focused), but if you enable focus stealer it will move focus to page instead

**Comment by wedevafrica** [comment]
@OlegWock that did the trick! Thank you so much!!!
