### ISSUE TITLE
Ability to create custom themes

### ISSUE THREAD

**Issue by godvlader** [OlegWock/anori#44]
Would be cool if y'all would add an option to add custom images for the backgrounds. I tried some workarounds but the extension crashed and i had to repair from google store. Is there any way i could do it by myself?

**Comment by OlegWock** [comment]
Not at the moment, but I'll consider adding ability to create custom themes 🤔

**Comment by OlegWock** [comment]
Requested in #99

* User should be able to select blur intensity
* Maybe support video backgrounds too

**Comment by OlegWock** [comment]
Hello! This should be added in version 1.17.0. I'll upload it to stores today, but it will take a few more days to get it published. After update you'll find 'Create custom theme' button in Settings > Themes menu
