### ISSUE TITLE
Todo widget - text wrap

### ISSUE THREAD

**Issue by rholdos** [OlegWock/anori#46]
Todo widget items text is always just 1 line, longer text parts are not visible.

Is it possible to show the whole text and wrap it with line breaks?
Or limit it with some maxLength (limit for number of characters) and truncate the shown part of text with "..."?

PS: Nice extension, keep it up 💪

**Comment by OlegWock** [comment]
ďakujem! If I remember correctly there were som issues with wrap previously, but I'll check what can be done there

**Comment by OlegWock** [comment]
Thank you for your report :) 

This should be fixed/added in v1.6.0. I sent new version to Google & Mozilla, but it might take up to a few days for it to get deployed. After that your extension will be automatically updated. Feel free to reopen/create new issue if something doesn't work.
