### ISSUE TITLE
Ability to move/copy widgets from one folder to another

### ISSUE THREAD

**Issue by ZadokhinDima** [OlegWock/anori#48]
I have a lot of bookmarks and decided to create a new folder for some of them. As a workaround I just exported the layout and edited the json, but would be nice to have such feature.

**Comment by OlegWock** [comment]
Hello @ZadokhinDima! This was implemented in recent version v1.11.0+
I already uploaded it to store, so if you have Anori installed it should update automatically after Google reviews this update

Feel free to comment/reopen if something doesn't work
