### ISSUE TITLE
YouTube search button looks for domain that doesn't exist

### ISSUE THREAD

**Issue by cjrivard** [OlegWock/anori#5]
When searching for 'Rick Astley', the search tries to use yt.com and produces an error:

> We can’t connect to the server at www.yt.com.
> 
> If you entered the right address, you can:
> 
>     Try again later
>     Check your network connection
>     Check that Firefox has permission to access the web (you might be connected but behind a firewall)

**Comment by OlegWock** [comment]
Thanks for report, this is now fixed in v1.0.5 

After new version gets approved by Google & Mozilla, it will update automatically
