### ISSUE TITLE
(suggestion) Calendar widget

### ISSUE THREAD

**Issue by fei1805** [OlegWock/anori#50]
Hi, thank you for creating anori. I want to suggest that users add events to their calendar widget and add custom colors to each of them.  when a user wants to check their event, they can do so by just hovering over the date and the event's name will appear. That's all, I hope you can take this into consideration.

**Comment by OlegWock** [comment]
Hello @fei1805. Thanks for you suggestion. I think this will be pretty much covered by Google Calendar integration (#45)?

**Comment by OlegWock** [comment]
After consideration, I think Anori will integrate with existing Calendar services (Google Calendar as top priority, and maybe Outlook some time after) instead of making our own events system, as I believe that would be more convenient for most of the users
