### ISSUE TITLE
Custom picture plugin

### ISSUE THREAD

**Issue by joannanicolewang** [OlegWock/anori#52]
Hi there! First of all, big thanks to you for creating this Chrome extension! Means a lot to me as it can boost my productivity. However, I would like to suggest some features for Anori!

1. Custom photo extension - so we may place our own photo for motivation
2. Custom theme or background color - so we may adjust the color to our own liking
3. Custom font & font size
4. Bigger date & time widget

That's all for now and I'm looking forward to your future updates! Cheers!

**Comment by OlegWock** [comment]
Hello @joannanicolewang. I'm glad you liked it. I prefer to have separate issues for each function, so I gonna split this issues into multiple:

Custom photo extension -> this issue
Custom theme or background color -> already tracked in #44 
Custom font & font size -> #55 (but I'm not sure if this will be added)
Bigger date & time widget -> #54

**Comment by OlegWock** [comment]
This was added in v1.18.0 (you should get this update automatically by this time), so closing this issue
