### ISSUE TITLE
Remove flashing "Fresh start" widget while loading new tab

### ISSUE THREAD

**Issue by qustrolabe** [OlegWock/anori#61]
Opening new Anori tab enough fast on my laptop but for split second I can see that before it actually loads my widgets there's just "Fresh start, huh?" widget. I think it would be visually better to see no widgets during this loading phase.

**Comment by OlegWock** [comment]
Hello @qustrolabe . I just uploaded new version of the extension (v1.7.1) to store. This version fixes flickering. It took a bit more time than I expected to prepare this release, but better late than never haha

Please note that it will take a few days for Google to review new version and for your browser to pull it from store. This process is automatic, so you don't need to do anything to update, just to wait a bit
