### ISSUE TITLE
Add and "Add" button on top sites.

### ISSUE THREAD

**Issue by Anjaan-g** [OlegWock/anori#62]
Currently, the top sites bar only imports the top sites from Chrome's top sites API. It would be actually beneficial if we could add our own sites in the top sites instead of bookmarks to easily organize our workflow.

**Comment by OlegWock** [comment]
This widget intended only to display top sites from Chrome and I'd prefer to keep its single purpose. If you want to add your own sites -- bookmark widget is what you should use.
