### ISSUE TITLE
Allow us to resize Widgets that are big like calendar

### ISSUE THREAD

**Issue by SupremeMedo** [OlegWock/anori#63]
So to start with it i wanna thank you at first for making such an awesome extension that lets your new tab look elegant but there is an issue with it whereas you cant change the size of the widgets, i wanna fit it in a small place and i wanna add another widgets and i dont think it will be possible if i add alot lol,
proof : 
![image](https://github.com/OlegWock/anori/assets/113359949/a7e57f1d-39cb-41c3-8f1a-1dfc1da67908)

**Comment by OlegWock** [comment]
Hello! Thank you and sorry for late answer. I agree this is nice to have feature (and at some point I'll add it), but it's technically challenging to implement (and will require more work to ensure each widget can work with all different sizes). As I don't have much time to spend on this project, I'm currently devoted to fixing bugs and adding new widgets.
