### ISSUE TITLE
downloading stuff will remove widgets temporairly 

### ISSUE THREAD

**Issue by SupremeMedo** [OlegWock/anori#64]

**Comment by OlegWock** [comment]
Yeah, when downloads section is shown, page has less real estate dedicated to it. And this in turn might change how many widgets Anori cat fit vertically. If there isn't enough space for widget in location it was initially added to, Anori will try to reposition it in free space. But if there isn't enough free space widget will be hidden.

I don't think there is something we can do to fix this problem, so I'm going to close thins issue.
