### ISSUE TITLE
Focus on search bar widget on open

### ISSUE THREAD

**Issue by RobbertjanV** [OlegWock/anori#66]
(suggestion) Focus on google bar when opening new tab so it's possible to start typing when the new tab has been opened. Just like the normal google chrome new tab

**Comment by OlegWock** [comment]
Hello @RobbertjanV! Just to make sure I understand you right, do you mean this search bar inside widget? 

![CleanShot 2023-05-26 at 22 39 56](https://github.com/OlegWock/anori/assets/7430438/3c78a4a2-03e8-4324-bd47-2739c40b049f)

**Comment by RobbertjanV** [comment]
Hi @OlegWock  Yes!

**Comment by OlegWock** [comment]
@RobbertjanV search bar on your screenshot should be focused by default. Looking at your URL it seem you have 'Focus stealer' enabled in settings. It's purpose is actually just opposite (to move focus from bar to page). If you wan't search bar to be focused you'll need to disable focus stealer

**Comment by OlegWock** [comment]
Re focusing on search widget, I'm not sure how to implement that properly in relation to other widgets (e.g. some users might want for tasks to be auto-focused, or notes). So I'd keep this issue open and see if there is interest to this feature

**Comment by RobbertjanV** [comment]
Hi thanks for the information about the focus stealer, if you ever think about implementing the auto focus on your custom search bar, you can also make it a setting so people can choose on which widget the focus gets
