### ISSUE TITLE
Additional settings

### ISSUE THREAD

**Issue by okeo1295** [OlegWock/anori#67]
Hello, I would have a few ideas:

— Possibility to rename the tab from “Anori new Tab”.
— Possibility to turn off the pen in the top right corner (in settings or as hotkey).

**Comment by OlegWock** [comment]
Hello @okeo1295. I just uploaded new version of the extension (v1.7.1) to store. This version includes both settings you suggested. It took a bit more time than I expected to prepare this release, but better late than never haha

Please note that it will take a few days for Google to review new version and for your browser to pull it from store. This process is automatic, so you don't need to do anything to update, just to wait a bit
