### ISSUE TITLE
Sites don't open

### ISSUE THREAD

**Issue by briansolms** [OlegWock/anori#78]
![image](https://github.com/OlegWock/anori/assets/135335185/bdb51119-3df0-4806-8173-4562e6fba106)
When I click on any of these sites they do not open. Please help.

**Comment by OlegWock** [comment]
They aren't supposed to open. When you click on icon it will switch search engine. And after you type your search query and hit enter or magnifier icon it will perform search on selected site. E.g. Click on youtube -> enter query -> click magnifier icon -> page with youtube search results opens
