### ISSUE TITLE
I need help again. So sorry

### ISSUE THREAD

**Issue by briansolms** [OlegWock/anori#80]
For the top sites, I did what you said but maybe I made a mistake somewhere cause now I only get this.
![image](https://github.com/OlegWock/anori/assets/135335185/6dbbc54a-fb0a-4e40-96cf-628ac8b8da15)

**Comment by OlegWock** [comment]
Anori takes this data directly from Chrome. It seems Chrome just doesn't think you visit particular sites often enough to consider them 'top sites'. If you would like to add some particular sites to new tab you can use bookmark widget

**Comment by briansolms** [comment]
Thank you. I really appreciate your help

Kind regards
Brian Solms
061 218 5960
________________________________
