### ISSUE TITLE
Opening links to a new tab

### ISSUE THREAD

**Issue by xreverx** [OlegWock/anori#97]
Hello!

Is there a way were every time you click a link on the dashboard it will open to a new tab or window?

**Comment by OlegWock** [comment]
Hi!

I believe you can open bookmarks in new tab if you do Cmd+click (on mac) or Ctrl+click (on windows/linux). And sometimes if you click with your mouse wheel this will open tab in a new tab, but I'm not sure how well this works across different platforms.

Does this solve your problem or did you mean like a separate option to always open bookmarks in a new tab?
