### ISSUE TITLE
Style Improvement suggestion

### ISSUE THREAD

**Issue by the-dragon-hub** [OlegWock/anori#99]
Hello, thanks for the great work!
I believe the extension would be even better if it has some modern style not classical as it is now.
something like this one maybe -https://chrome.google.com/webstore/detail/ultimate-new-tab-with-cal/cmfhopmhaagcfnjflfppceclmkenjkpc- just the transparent background style and not too blurry with the option to add custom backgrounds and video backgrounds.
and it would be a huge plus if you added voice search option at the search bar widget, search suggestions and the option to freely resize the widget.
please consider these points asap.
*I'm using it on edge.
thanks.

**Comment by OlegWock** [comment]
Hello! Thanks for your feedback.

Anori has its own style which was a conscious choice, and I currently don't plan to change it drastically. 

Feature to create custom themes (including custom backgrounds) is tracked here: https://github.com/OlegWock/anori/issues/44

Option to freely resize widgets currently is currently not in the nearest plans, it's technically challenging to implement (and will require more work to ensure each widget can work with all different sizes). As I don't have much time to spend on this project, I'm currently devoted to fixing bugs and adding new widgets.

Voice search not in the plans yet, as it also required quite a bit of work. As for search suggestions, I created new issue to track it https://github.com/OlegWock/anori/issues/100
If you would like to get notifications about activity regarding this feature, you can click 'subscribe' on that issue page
